spring.application.name=buying-ticket-system
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=ticket_user
spring.datasource.password=change_me
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=always

# Enable SQL logging for easier debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
